 # install.packages('data.table')
 # install.packages('stringr')
 # install.packages('ltm')
 # install.packages('catR')
 # install.packages('mirt')
 # install.packages('foreach')
 # install.packages('sfsmisc')
 # install.packages('iterators')
 # install.packages('profvis')
 # install.packages('scoring')
 # install.packages('binom')
 # install.packages('pryr')
 # install.packages('penalized')
 # install.packages('splitstackshape')
 # install.packages("backports")
 # install.packages("tidyverse")
 # install.packages("testthat")

# library('testthat')
library('tidyverse')
library('data.table')
library('stringr')
library('ltm')
library('catR')
library('mirt')
library('foreach')
library('sfsmisc')
library('iterators')
library('profvis')
library('scoring')
library('binom')
library('pryr')
library('penalized')
library('splitstackshape')

options(scipen=500) # Don't print scientific notation for large numbers

source("src/main/R/location_functions.R")
source("src/main/R/question_functions.R")
source("src/main/R/answer_functions.R")
source("src/main/R/utility_functions.R")
source("src/main/R/analysis_functions.R")
source("src/main/R/irt_functions.R")
source("src/main/R/pfa_functions.R")
source("src/main/R/stats_functions.R")


